// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjm-IKIJhgJO-TGc9kmpgIcFmZqtbVORg',
    appId: '1:822316430389:web:7ff1f86b9ce4603237ad7c',
    messagingSenderId: '822316430389',
    projectId: 'rig-power-calculator',
    authDomain: 'rig-power-calculator.firebaseapp.com',
    storageBucket: 'rig-power-calculator.appspot.com',
    measurementId: 'G-MV05C54JE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMCPUXdV5M6Tn3mGWK-bB6KexKZuBLNqw',
    appId: '1:822316430389:android:243df9a05642a9d737ad7c',
    messagingSenderId: '822316430389',
    projectId: 'rig-power-calculator',
    storageBucket: 'rig-power-calculator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvrX6fikWJDvD6D14lOz8YDJkoiVS3OkI',
    appId: '1:822316430389:ios:fa0e5d98c65f3e7937ad7c',
    messagingSenderId: '822316430389',
    projectId: 'rig-power-calculator',
    storageBucket: 'rig-power-calculator.appspot.com',
    iosClientId: '822316430389-505th99jc5meoomq83ge4v3l30qoe5ci.apps.googleusercontent.com',
    iosBundleId: 'com.example.rigPowerCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvrX6fikWJDvD6D14lOz8YDJkoiVS3OkI',
    appId: '1:822316430389:ios:13104f9092d0f20d37ad7c',
    messagingSenderId: '822316430389',
    projectId: 'rig-power-calculator',
    storageBucket: 'rig-power-calculator.appspot.com',
    iosClientId: '822316430389-kir40gfaqs1crp84u6ka3l5lsq3d63d5.apps.googleusercontent.com',
    iosBundleId: 'com.example.rigPowerCalculator.RunnerTests',
  );
}
